### ISSUE TITLE
[question ]is this lib support  openfl  or heaps?

### ISSUE THREAD

**Issue by sonygod** [nadako/hxspine#7]
[question ]is this lib support openfl or heaps?

are there any examples?

**Comment by sh-dave** [comment]
It's a logic only library, you have to write a renderer for the framework you're going to use. I have a WIP one for Kha (not yet public), and it was actually quite easy to do. I used the [spine-ts webgl runtime](https://github.com/EsotericSoftware/spine-runtimes/tree/3.8/spine-ts) as a starting point. 

For openfl you could maybe port the spine-as3 runtime easier?

**Comment by nadako** [comment]
What he said :)
